time: 2021-08-27 20:58:05.669988  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-27 20:58:05.670985  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 41, in valera_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-27 20:58:05.670985  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-27 20:58:05.670985  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-27 20:58:05.671983  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 41, in valera_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
