time: 2021-08-27 20:58:05.669988  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-27 20:58:05.670985  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 41, in valera_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-27 20:58:05.670985  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-27 20:58:05.670985  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-27 20:58:05.671983  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 41, in valera_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:44:12.718220  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:44:12.719218  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 49, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:44:12.719218  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 41, in valera_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:44:12.719218  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 48, in grisha_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:44:12.719218  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:44:12.720216  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 49, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:44:12.720216  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 42, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:44:12.720216  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 30, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 49, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:48:34.003107  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 46, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:48:34.003107  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 56, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:48:34.003107  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 45, in valera_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:48:34.004076  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 55, in grisha_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:48:34.004076  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 46, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:48:34.004076  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 56, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:48:34.005074  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 46, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:48:34.005074  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 56, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:49:50.557174  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 48, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:49:50.557174  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 60, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:49:50.558171  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 47, in valera_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:49:50.558171  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 59, in grisha_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:49:50.558171  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 48, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:49:50.588119  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 60, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:49:50.589088  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 48, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:49:50.589088  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 60, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:50:03.423097  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 48, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:50:03.424095  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 60, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:50:03.424095  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 47, in valera_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:50:03.424095  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 59, in grisha_go    raise ValueError('Функция валераГоу предназначена только для целых чисел')ValueError: Функция валераГоу предназначена только для целых чисел
time: 2021-08-28 00:50:03.425092  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 48, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:50:03.441081  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 60, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
time: 2021-08-28 00:50:03.442047  func_name: valera_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 48, in valera_go    return 10 / numberZeroDivisionError: division by zero
time: 2021-08-28 00:50:03.442047  func_name: grisha_go ERROR: Traceback (most recent call last):  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 31, in wrapped_func    func_to_call = func(*args, **kwargs)  File "C:\Users\Гриша\PycharmProjects\python_27_skillbox\27_zadacha_3\main.py", line 60, in grisha_go    return 10 / number + 25ZeroDivisionError: division by zero
